### ISSUE TITLE
LG C2 turns on, but not off

### ISSUE THREAD

**Issue by Knud3** [JPersson77/LGTVCompanion#211] opened 2024-04-27 00:03 UTC
Coincidence or not, but I just updated LGTV Companion, and now I can't turn TV off anymore. Waking up works fine. TV is connected via WiFi and have latest updates.

When sending turn off signal, I can see single TCP SYN packet to port 3001, but nothing happening.

```
Sat 02:53:58 > -poweroff Device1
Sat 02:53:58 > [IPC] Force power OFF: Device1 
Sat 02:53:58 > Device1, spawning Thread_DisplayOff().
Sat 02:54:19 > Device1, WARNING! Thread_DisplayOff(): connect: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond [system:10060 at D:\a\LGTVCompanion\LGTVCompanion\vcpkg_installed\x64-windows-static\x64-windows-static\include\boost\asio\detail\win_iocp_socket_service.hpp:629:5 in function 'connect']
```

**Comment by JPersson77** [comment] 2024-04-27 07:28
Hi can you please paste the full log and config.json (c:/programdata/lgtv companion/ ) to pastebin or similar and I will have a look

**Comment by Knud3** [comment] 2024-04-27 14:02
For addittional information TV is in another subnet and pfSense is routing trafic. It have worked well for over year now and I haven't changed a thing.

Log for full test cycle:
```
Sat 16:52:26 > -poweroff Device1
Sat 16:52:26 > [IPC] Force power OFF: Device1 
Sat 16:52:26 > Device1, spawning Thread_DisplayOff().
Sat 16:52:30 > -poweron Device1
Sat 16:52:30 > [IPC] Force power ON: Device1 
Sat 16:52:30 > Device1, spawning Thread_DisplayOn().
Sat 16:52:30 > Device1, repeating WOL broadcast started to MAC: REDACTED using IP address: 10.14.16.50
Sat 16:52:30 > Device1, Best route to IP - interface index 13 LUID REDACTED route protocol 3; route is not local, aborting!
Sat 16:52:47 > Device1, WARNING! Thread_DisplayOff(): connect: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond [system:10060 at D:\a\LGTVCompanion\LGTVCompanion\vcpkg_installed\x64-windows-static\x64-windows-static\include\boost\asio\detail\win_iocp_socket_service.hpp:629:5 in function 'connect']
Sat 16:52:51 > Device1, WARNING! Thread_DisplayOn(): connect: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond [system:10060 at D:\a\LGTVCompanion\LGTVCompanion\vcpkg_installed\x64-windows-static\x64-windows-static\include\boost\asio\detail\win_iocp_socket_service.hpp:629:5 in function 'connect']
Sat 16:53:11 > Device1, repeating WOL broadcast ended
Sat 16:53:12 > Device1, WARNING! Thread_DisplayOn(): connect: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond [system:10060 at D:\a\LGTVCompanion\LGTVCompanion\vcpkg_installed\x64-windows-static\x64-windows-static\include\boost\asio\detail\win_iocp_socket_service.hpp:629:5 in function 'connect']
```

config.json
```
{
    "Device1": {
        "Enabled": true,
        "HDMIinputcontrol": false,
        "IP": "10.14.16.50",
        "MAC": [
            "REDACTED"
        ],
        "Name": "LGC2",
        "NewSockConnect": true,
        "OnlyTurnOffIfCurrentHDMIInputNumberIs": 1,
        "SessionKey": "REDACTED",
        "SetHDMIInputOnResume": false,
        "SetHDMIInputOnResumeToNumber": 1,
        "Subnet": "255.255.255.0",
        "WOL": 2
    },
    "LGTV Companion": {
        "AdhereDisplayTopology": false,
        "AutoUpdate": true,
        "BlankWhenIdle": true,
        "BlankWhenIdleDelay": 10,
        "ExtendedLog": true,
        "ExternalAPI": false,
        "IdleFsExclusionsEnabled": false,
        "IdleFullscreen": true,
        "IdleWhiteListEnabled": false,
        "KeepTopologyOnBoot": false,
        "MuteSpeakers": false,
        "PowerOnTimeOut": 40,
        "RemoteStream": false,
        "RemoteStreamPowerOff": true,
        "TimingPreshutdown": false,
        "Version": 2
    }
}
```

![2024-04-27 16_55_01-Status_ System Logs_ Firewall_ Normal View - fw home lan — LibreWolf](https://github.com/JPersson77/LGTVCompanion/assets/62902464/1d1bde6b-ac78-47f4-9b2f-fad29c4fa105)

**Comment by JPersson77** [comment] 2024-04-27 14:08
There is very limited information in the log snippet. The info is that the connection attempt failed.

Using a web browser, do you see a "hello world!" if you go to https://IP:3001 ? 

Or click here: [local IP https://10.14.60.50:3001](https://10.14.60.50:3001) ) and ignore the warning about unsafe connection.

**Comment by Knud3** [comment] 2024-04-27 14:24
```
curl https://10.14.16.50:3001
curl : Unable to connect to the remote server
```

It seems that TV is not even listening that port. Tested from router itself:

![2024-04-27 17_16_00-Diagnostics_ Test Port - fw home lan — LibreWolf](https://github.com/JPersson77/LGTVCompanion/assets/62902464/dbc6ca73-9d7d-4d86-9e09-58f3c0afe3fd)

TV is connected to WiFi and as said waking up is working fine:

![20240427_171320](https://github.com/JPersson77/LGTVCompanion/assets/62902464/d65c43e7-6c0e-482b-a81a-94e9f94ebb30)

I tried to re-enable `TV On With Mobile` function and add device again to LGTV Companion, but it did not help.

**Comment by JPersson77** [comment] 2024-04-27 16:07
Try to pull the plug on the the TV, if that does not work try to power c ycle all network equipmemt including router, acesspoints, switches... 

Seen it help with similar weird issues

**Comment by JPersson77** [comment] 2024-04-29 15:06
There should not really be a setting on the TV which disable the ability to do a socket-connect to it. (Waking up does not require a connection as it is udp/broadcast wol so that explains why that still works)

Can you try on the actual subnet? Ie bypassing router forwards?

**Comment by thee3Xiled** [comment] 2024-05-03 11:07
> I tried, but did not help. Only waking up works.

Hey, were you by any chance able to fix this issue? I'm having the same one.

**Comment by JPersson77** [comment] 2024-05-03 11:11
It is not clear what the issue is. It seems that the TV does not respond  (to anything) or that the router does not forward packets properly. 

@thee3Xiled maybe start a new issue, paste your log and I will have a look.

**Comment by JPersson77** [comment] 2024-05-04 21:02
ok thanks for feedback. closing the issue, but will make sure to remember the solution

**Comment by JPersson77** [comment] 2024-05-08 13:04
Hey, from the log it looks better. No signs of the app not being able to communicate as far I did see. If the TV does not wake up that should now be because the magic packets  are not reaching it.

From current issues I noticed there seems to be compatibility issues with ESET internet security and WOL, are you using that by any chance? 

Additionally I'm working on rewriting the backend and there is currently a development build on discord if you would like to see if that helps. There is some positive feedback, but it will depend on what your actual issue is ofcourse. https://discord.gg/7KkTPrP3fq

**Comment by JPersson77** [comment] 2024-05-18 07:40
Just circling back to this. Any feedback wrt using ESET? Does v4.0.0 of the app make any difference to the issue?

**Comment by Knud3** [comment] 2024-05-18 15:40
Sorry, I forgot to answer. No, I do not have ESET. I updated to v4.0.0 yesterday and I did had problem to get TV to sleep. But today it is working...

**Comment by Knud3** [comment] 2024-05-18 15:41
Maybe I need to keep log for problems. Or does it even help if application log does not show any problems?

**Comment by JPersson77** [comment] 2024-06-02 07:32
Hi @Knud3 any more feedback wrt this issue? Is v4 working for you?

**Comment by JPersson77** [comment] 2024-06-04 15:09
Closing due to lack of feedback, please feel free to reopen as necessary

**Closed by JPersson77** 2024-06-04 15:09 UTC

**Comment by Knud3** [comment] 2024-06-17 15:56
Sorry for not inputing my feedback earlier. I just build new PC and finished it couple days ago. Disk and OS installation are same. Things have worked smoothly for now.

What have changed in setup:
- New MB and CPU (NIC `Intel I219-V Gigabit` to `Marvell AQtion 10Gbit`)
- Newest LGTV Companion (`v4.x.x` to `v4.0.3`)
- Enabled `Persistent + Keep Alive` persistence

**Comment by JPersson77** [comment] 2024-06-17 18:12
Fingers crossed it keeps on running smoothly
