### ISSUE TITLE
Can't enable multi-monitor topology

### ISSUE THREAD

**Issue by shiftydev** [JPersson77/LGTVCompanion#179] opened 2023-11-09 12:26 UTC
Hello, I cannot enable support for multi-monitor topology as the program tells me no WebOS devices are detected. This is despite the device being setup and managed by LG TV Companion.

Running Windows 11 with LG C2 42 with Always Ready enabled. The screenshot was taken on the C2 running extended desktop, as instructed.

It may be related that I had to manually add the device with IP and MAC address since the scan function did not detect it.

![Screenshot 2023-11-09 130233](https://github.com/JPersson77/LGTVCompanion/assets/2463373/f53def2d-b9f5-48e9-bf72-4216828f63fb)

**Comment by JPersson77** [comment] 2023-11-09 13:00
Hi @shiftydev can you confirm the TV is connected via HDMI as well? (I guess there are some use cases where it is not - but this function is dependent on the device being physically connected )

The app is iterating through the details of enabled devices looking for a particular string ("LG TV"). Can you please check whether the device is available in device manager under digital media devices  and if so go into properties of the TV and check the values in the details drop down box: for the following items and type the respective strings here:  association endpoint model name, model, pnp-x model name

**Comment by shiftydev** [comment] 2023-11-09 13:39
The TV is indeed connected with HDMI to an Nvidia RTX 4080. The friendly name under Monitors in Device Manager is `Generic Monitor (LG TV SSCR2)`.

**Comment by JPersson77** [comment] 2023-11-09 18:22
Can you click into properties as well please and go to the details tab and use the drop down box and see what the "Friendly name" is there please

**Comment by shiftydev** [comment] 2023-11-09 18:28
That is what I did.
![Screenshot 2023-11-09 192625](https://github.com/JPersson77/LGTVCompanion/assets/2463373/adfa2597-9ef0-493d-b8a1-97df8da9aea7)

**Comment by shiftydev** [comment] 2023-11-09 19:21
No problem. On there with same username. Let me know what you need me to do.

**Comment by JPersson77** [comment] 2023-11-12 10:47
After some troubleshooting the issue was likely caused by having renamed the device using CRU. Closing the issue, but feel free to reopen as necessary

**Closed by JPersson77** 2023-11-12 10:47 UTC
