### ISSUE TITLE
Screen restoration prompt appears on wakeup

### ISSUE THREAD

**Issue by wrinkledeth** [JPersson77/LGTVCompanion#97] opened 2023-01-10 14:03 UTC
Whenever my C2 screen is blanked out my LGTV Companion due to inactivity, if I wait too long to wake it back up, I am shown [this popup](https://i.redd.it/gwarkeqrrh191.jpg): "To provide the clearest picture, TV needs to start screen restoration (yes/no prompt)"

I assume this is happening because the TV was not actually turned off. 

Is there any way to avoid seeing this popup? Not sure if I am doing something wrong.

**Comment by JPersson77** [comment] 2023-01-10 14:51
Hi @wrinkledeth this is the TV informing you that it needs to do pixel cleaning. It's routine maintenance that LG had implemented to ensure the stability of the image. I've see it too. Usually you click 'yes' and it does its thing. Let the TV remain off for a while so it has time to finish. Then it should not pop up anymore (until its time again)

**Comment by wrinkledeth** [comment] 2023-01-11 23:04
Thank you for your response! 

Okay I see, on average, how often does the popup show up for you? 

I will close this issue now as it is clearly not something that can be addressed by your software.

**Comment by JPersson77** [comment] 2023-01-12 11:49
I've seen it once in a  year only

**Comment by huynhj93** [comment] 2024-02-23 07:53
Just a note on this, the software seems to cancel the screen restoration after 5-20s so i had to click the "Manage this device" to stop it from managing, and then do the screen restore.

**Comment by JPersson77** [comment] 2024-02-23 10:02
That sounds weird. Its definitely not by design but unforseen consequences might happen. 

Any chance you can enable logging, take note on relevant time codes and paste the info here?

**Comment by huynhj93** [comment] 2024-02-24 03:28
sure can! let me try reproducing but i dont get the prompt anymore, i'll manually trigger it

**Comment by huynhj93** [comment] 2024-02-24 03:44
Can't reproduce the issue if i manually trigger the screen restoration! If it prompts me to do it in the next 6 months and the behavior occurs again, I'll make sure to grab the logs.

**Comment by JPersson77** [comment] 2024-02-24 10:27
Thanks!

**Comment by JPersson77** [comment] 2024-06-16 18:50
Closing this issue, but please feel free to reopen as necessary

**Closed by JPersson77** 2024-06-16 18:50 UTC

**Comment by msderganc** [comment] 2025-03-26 13:34
Hi - I am having this issue as well - I will post a log snippet below. Ideally, I'd love to have the screen do a restoration (by shutting off completely) overnight or when idle for a long period of time (or even when scheduled). I usually have to disable LG Companion to manually shut off the screen and let it process

`[Sun Mar 23 08:26:35][-I--][  System   ]  --- LGTV Companion Service has started (v 4.4.5) ---------------------------
[     .        .    ][-I--][    PWR    ]  *** System requests displays to power on
[     .     08:28:17][--W-][[LG] webOS ]  Finished retrying connection
[     .     09:09:29][-I--][ Daemon 1  ]  User is idle
[     .     09:09:38][--W-][[LG] webOS ]  Retried twice but failed to perform work of type 3. Aborting!
[     .     09:18:25][-I--][ Daemon 1  ]  User is not idle
[     .     09:20:06][--W-][[LG] webOS ]  Finished retrying connection
[     .     11:36:51][-I--][    PWR    ]  *** System requests displays to power off (dimmed)
[     .     11:37:06][-I--][    PWR    ]  *** System requests displays to power off
[     .     11:37:09][--W-][[LG] webOS ]  Retried twice but failed to perform work of type 2. Aborting!
[     .     11:41:56][-I--][    PWR    ]  *** System requests displays to power on
[     .     11:43:37][--W-][[LG] webOS ]  Finished retrying connection
[     .     11:58:50][-I--][ Daemon 1  ]  User is idle
[     .     11:58:59][--W-][[LG] webOS ]  Retried twice but failed to perform work of type 3. Aborting!
[     .     12:07:53][-I--][    PWR    ]  *** System requests displays to power off (dimmed)
[     .     12:08:08][-I--][    PWR    ]  *** System requests displays to power off
[     .     12:08:11][--W-][[LG] webOS ]  Retried twice but failed to perform work of type 2. Aborting!
[     .     12:08:13][-I--][    PWR    ]  *** System requests displays to power on
[     .     12:09:55][--W-][[LG] webOS ]  Finished retrying connection
[     .     12:44:15][--W-][[LG] webOS ]  Retried twice but failed to perform work of type 3. Aborting!
[     .     12:49:53][-I--][    PWR    ]  *** System requests displays to power off (dimmed)
[     .     12:50:08][-I--][    PWR    ]  *** System requests displays to power off
[     .     12:50:11][--W-][[LG] webOS ]  Retried twice but failed to perform work of type 2. Aborting!
[     .     15:30:22][-I--][    PWR    ]  *** System is suspending to a low power state (or event log entry is missing)
[     .     16:19:28][-I--][    PWR    ]  *** System is resuming from low power state
[     .        .    ][-I--][    PWR    ]  *** System requests displays to power on
[     .     16:19:30][-I--][    PWR    ]  *** System is resuming from low power state (Automatic)
[     .     16:21:10][--W-][[LG] webOS ]  Finished retrying connection
[     .     19:19:48][-I--][    PWR    ]  *** System requests displays to power off (dimmed)
[     .     19:20:03][-I--][    PWR    ]  *** System requests displays to power off
[     .     19:20:06][--W-][[LG] webOS ]  Retried twice but failed to perform work of type 2. Aborting!
[     .     19:34:42][-I--][ Daemon 1  ]  User is idle
[     .     19:41:51][-I--][    PWR    ]  *** System requests displays to power on
[     .     19:43:32][--W-][[LG] webOS ]  Finished retrying connection
[     .     22:42:33][--W-][[LG] webOS ]  Retried twice but failed to perform work of type 3. Aborting!
[     .     22:47:08][-I--][    PWR    ]  *** System requests displays to power off (dimmed)
[     .     22:47:23][-I--][    PWR    ]  *** System requests displays to power off
[     .     22:47:26][--W-][[LG] webOS ]  Retried twice but failed to perform work of type 2. Aborting!
[Mon Mar 24 01:27:51][-I--][    PWR    ]  *** System is suspending to a low power state (or event log entry is missing)
[     .     07:37:35][-I--][    PWR    ]  *** System is resuming from low power state
[     .        .    ][-I--][    PWR    ]  *** System requests displays to power on
[     .     07:37:37][-I--][    PWR    ]  *** System is resuming from low power state (Automatic)
[     .     07:39:00][-I--][    PWR    ]  *** System requests displays to power off
[     .     07:39:16][--W-][[LG] webOS ]  Finished retrying connection
[     .     07:39:20][--W-][[LG] webOS ]  Retried twice but failed to perform work of type 2. Aborting!
[     .     07:52:35][-I--][ Daemon 1  ]  User is idle
[     .     08:03:05][-I--][    PWR    ]  *** System requests displays to power on
[     .     08:04:46][--W-][[LG] webOS ]  Finished retrying connection
[     .     22:56:20][--W-][[LG] webOS ]  Retried twice but failed to perform work of type 3. Aborting!
[     .     23:11:19][--W-][[LG] webOS ]  Retried twice but failed to perform work of type 3. Aborting!
[     .     23:19:49][-I--][    PWR    ]  *** System requests displays to power off (dimmed)
[     .     23:20:04][-I--][    PWR    ]  *** System requests displays to power off
[     .     23:20:07][--W-][[LG] webOS ]  Retried twice but failed to perform work of type 2. Aborting!
[Tue Mar 25 01:42:28][-I--][    PWR    ]  *** System is suspending to a low power state (or event log entry is missing)
[     .     07:47:39][-I--][    PWR    ]  *** System requests displays to power on
[     .     07:47:40][-I--][    PWR    ]  *** System is resuming from low power state
[     .        .    ][---E][  System   ]  I/O Context did not finish work during the previous system suspend.
[     .     07:47:43][-I--][    PWR    ]  *** System is resuming from low power state (Automatic)
[     .     07:49:46][-I--][    PWR    ]  *** System requests displays to power off
[     .     07:49:49][--W-][[LG] webOS ]  Retried twice but failed to perform work of type 2. Aborting!
[     .     07:54:09][-I--][    PWR    ]  *** System requests displays to power on
[     .     07:55:50][--W-][[LG] webOS ]  Finished retrying connection
[     .     17:33:00][-I--][ Daemon 1  ]  User is idle
[     .     17:33:09][--W-][[LG] webOS ]  Retried twice but failed to perform work of type 3. Aborting!
[     .     17:37:45][-I--][    PWR    ]  *** System requests displays to power off (dimmed)
[     .     17:37:48][-I--][    PWR    ]  *** System requests displays to power on
[     .     17:39:30][--W-][[LG] webOS ]  Finished retrying connection
[     .     20:00:16][-I--][    PWR    ]  *** System requests displays to power off (dimmed)
[     .     20:00:31][-I--][    PWR    ]  *** System requests displays to power off
[     .     20:00:34][--W-][[LG] webOS ]  Retried twice but failed to perform work of type 2. Aborting!
[     .     20:05:11][-I--][    PWR    ]  *** System requests displays to power on
[     .     20:06:52][--W-][[LG] webOS ]  Finished retrying connection
[     .     23:03:52][--W-][[LG] webOS ]  Retried twice but failed to perform work of type 3. Aborting!
[     .     23:18:52][--W-][[LG] webOS ]  Retried twice but failed to perform work of type 3. Aborting!
[     .     23:19:48][-I--][    PWR    ]  *** System requests displays to power off (dimmed)
[     .     23:20:03][-I--][    PWR    ]  *** System requests displays to power off
[     .     23:20:06][--W-][[LG] webOS ]  Retried twice but failed to perform work of type 2. Aborting!
[Wed Mar 26 01:50:05][-I--][    PWR    ]  *** System is suspending to a low power state (or event log entry is missing)
[     .     07:23:39][-I--][    PWR    ]  *** System is resuming from low power state
[     .        .    ][-I--][    PWR    ]  *** System requests displays to power on
[     .     07:23:42][-I--][    PWR    ]  *** System is resuming from low power state (Automatic)
[     .     07:25:20][--W-][[LG] webOS ]  Finished retrying connection
[     .     07:41:54][-I--][ Daemon 1  ]  User is idle
[     .     07:42:03][--W-][[LG] webOS ]  Retried twice but failed to perform work of type 3. Aborting!
[     .     07:46:57][-I--][ Daemon 1  ]  User is not idle
[     .     07:48:38][--W-][[LG] webOS ]  Finished retrying connection`
