### ISSUE TITLE
Erratic behavior since 1.8

### ISSUE THREAD

**Issue by alamone** [JPersson77/LGTVCompanion#78] opened 2022-11-14 01:10 UTC
Hi, I have a dual monitor setup with LG CX 65 and LG C1 48, running Windows 11.  I was using 1.8 and it was generally working without issues.  Ever since I installed 1.9 it has been turning off my monitors at inappropriate times - e.g. at the windows login screen.  Other times, it was turning on my monitors after I manually turn them off - this was never an issue with 1.8.  I tried disabling the match to Windows topology feature and it is still having issues.  So I am uninstalling the program for the time being.

**Comment by alamone** [comment] 2022-11-14 01:13
Sorry I got my versions mixed up.  I am referring to 1.8 having issue, and 1.7 appearing to work fine.

**Comment by JPersson77** [comment] 2022-11-14 11:37
Hi @alamone if you want me to have a look, can you please upload a log to pastebin or similar and paste a link here? And also make sure to tell me the timecode of when erratic baehaviour is happenig. Cheers!

**Comment by ryanmoses** [comment] 2022-11-24 19:53
Hi @alamone  & @JPersson77  - I have the same issues.  I thought it was related to an IP addressing issue but I can confirm I have the exact issues described by @alamone with version v1.8

The TV powers on when I shut down the PC and it powers on at the windows login screen.  It will also power on at other seemingly random times.  EG when working during the day I remove my OLED Tv from monitor topology as I'm not using it - However it will power on multiple times throughout the day.

I will try get some logs!

Thanks!

**Comment by JPersson77** [comment] 2022-11-24 21:28
@alamone @ryanmoses logs would be of great assistance.

One thing though, it is expected that the displays power on for the login screen when booting. Once the user has logged in the displays should after a few seconds respect the monitor topology though. This behaviour is because the monitor topology is a  user space function.

**Comment by JPersson77** [comment] 2022-12-10 11:26
There is a development build v1.8.5 available on discord. This is a bugfix build with some changes to the power on/off logic that may resolve some issues noted in this thread. If you download and install this build please provide feedback on any observed changes in ability to keep power state between PC and display in sync and the specific fixes noted below.

bugfix for reported issues with random power on/off potentially related to wm_displaychange message handling in the v1.8 topology feature
made clear that change of GPU and / or adding displays may invalidate the topology configuration.
Implemented detection for invalidated topology configuration which will show windows notification and log message urging user to reconfigure.
added mechanism for identifying invalid pairing keys
more help texts was added to all configuration options in the UI
https://discord.gg/7KkTPrP3fq

**Comment by JPersson77** [comment] 2023-01-01 10:44
@alamone @ryanmoses I would be interested if you have any further input on this issue

**Comment by JPersson77** [comment] 2023-02-15 19:25
closing the issue due to missing feedback. Feel free to reopen as needed

**Closed by JPersson77** 2023-02-15 19:25 UTC
