### ISSUE TITLE
v2.1.0: bad Start Menu shortcut

### ISSUE THREAD

**Issue by MEGAtheguy** [JPersson77/LGTVCompanion#112] opened 2023-02-09 16:24 UTC
Updating to or fresh installing v2.1.0 puts a bad shortcut in the start menu. Opening directly from "C:\Program Files\LGTV Companion" works without error. Manually making a new shortcut and pasting it in "C:\ProgramData\Microsoft\Windows\Start Menu\Programs" resolves the issue as well

![LGTV Companion 2 1 0 error](https://user-images.githubusercontent.com/12264494/217872375-3f95af6c-f038-4778-b4ca-582341f92513.png)

**Comment by JPersson77** [comment] 2023-02-09 16:32
Hmm that was a weird issue, thanks for highlighting. What OS and build are you running?

**Comment by MEGAtheguy** [comment] 2023-02-09 16:33
Windows 11; Build 22621.1194

**Comment by JPersson77** [comment] 2023-02-09 16:34
Allright thanks, will investigate!

**Comment by JPersson77** [comment] 2023-02-09 18:17
Is the error reproducible?

**Comment by MEGAtheguy** [comment] 2023-02-09 20:04
Weirdly enough, now the issue is reproducible for v2.0.0 and v2.1.0. Not as relevant now but below is a video demonstrating to document anyway

https://user-images.githubusercontent.com/12264494/217921598-309c86e2-23a0-4b0d-8d54-036bd9ca04f6.mp4

**Comment by JPersson77** [comment] 2023-02-09 22:01
weird a f, I'm sure there is an issue somewhere but a t m don't know where. I reviewed the installer but there is nothing strange as far as I can see. I'lll keep this issue open and see what can be done

**Comment by JPersson77** [comment] 2023-06-09 20:23
Can't reproduce and no other reports of this issue has popped up so I'm going to close it. Feel free to reopen if needed

**Closed by JPersson77** 2023-06-09 20:23 UTC
