### ISSUE TITLE
TV Turn off while video playback.

### ISSUE THREAD

**Issue by Battler624** [JPersson77/LGTVCompanion#52] opened 2022-08-26 10:13 UTC
While playing local video files, the Automatic Blank feature still turns off the TV. I wish that this can be fixed.

Semi-related question, isn't it possible to hook into windows screensaver feature and if screensaver gets turned on then the LG Companion app would turn off (automatic blank) the TV? I'm asking because windows screensaver was what used before using the LGTV Companion and in that one regard its better and I'd honestly keep using it if the TV didn't turn off completely hours later and i'd have to use the remote.

**Comment by dechamps** [comment] 2022-08-26 10:55
> While playing local video files, the Automatic Blank feature still turns off the TV.

My understanding is that this is working as intended for this feature. See #13.

> Semi-related question, isn't it possible to hook into windows screensaver feature and if screensaver gets turned on then the LG Companion app would turn off (automatic blank) the TV?

I'm not sure I understand your use case. Currently with LGTVCompanion you have two options besides the "automatic blank" feature:

1. Use the "blank" Windows screensaver: sends a black signal to the TV when the Windows screensaver timeout kicks in. Prevents burn-in since no picture is displayed.
   - Downside: the TV is not turned off (and therefore still uses some power - I measured about 50W with my 77" G1).
   - Upside: the picture comes back instantly as soon as you move the mouse. Or:
2. Configure Windows power options to turn off the display after some time. LGTVCompanion will detect that Windows wants to turn off the display and will automatically send a "power off" command to the TV when that happens. When Windows wants to turn the display back on (e.g. because you moved the mouse), LGTVCompanion detects that as well and automatically turns the TV back on.
   - The TV is completely powered off in that case, so it uses no power, but that also means it takes a few seconds to get it running again.

Obviously you can also use both approaches at the same time which is what I do: blank screensaver after 3 minutes, turn off display after 30 minutes.

**Comment by JPersson77** [comment] 2022-08-26 10:55
Hi @Battler624 

1 This is actually by design, since the idea of the feature is to be a more "aggressively" configured screen saver. If you want windows/apps to be able to override/negate the screensaver, f e during gaming, watching a video etc then a normal blank windows screensaver can suffice. You are right that there is a case where you may have to use the remote and that is when th TV automatically turns itself off after some time, because windows does not know about it. To avoid the case where you have to use the remote to turn on the TV after it has been automatically shut off (by the TV itself) you can:
- either adjust the settings in the TV to never automatically turn the TV off, and/or
- Set windows power savings to turn off the TV after some time, maybe 30-60 minutes of idle. Then you can just wiggle the mouse to power on/activate the monitor again


2 And yes it's possible to detect when the screensaver launch but see my answer to 1 :)

**Comment by JPersson77** [comment] 2022-08-26 10:56
@dechamps you beat me to it :)

**Comment by Battler624** [comment] 2022-08-26 19:39
Thank you for you replies and #13 definitely shed some light on what I was thinking.

The whole idea about keeping the "auto poweroff" feature is to for the TV to run whatever OLED Care features it needs to run.

I'm going to follow what @dechamps is doing, it fits me exactly, again thank you both @dechamps @JPersson77.

I still do believe a middle-ground is doable (Companion app takes over if windows screensaver is detected, if not detected with 30 minutes of "idle" it'll do the automatic blank thing) but I totally dont mind the current stance

**Comment by JPersson77** [comment] 2023-01-01 10:10
Closing this issue since v1.9.0 implements more options for controlling the granularity of user idle mode and I don't have further plans to let the app hook onto the windows screensaver

**Closed by JPersson77** 2023-01-01 10:10 UTC
