### ISSUE TITLE
LG C2 no longer powering off after latest firmware 

### ISSUE THREAD

**Issue by dlfiz** [JPersson77/LGTVCompanion#141] opened 2023-05-27 12:29 UTC
Will no longer fully power off and sits in no signal state until timeout.

**Comment by JPersson77** [comment] 2023-05-27 15:00
Hi @dlfiz can you confirm the IP is still correctly configured (i e that the TV has not been assigned another ip by the router).  Please enable logging and upload log.txt and config.json to pastebin and copy the link here and I'll have a look

**Comment by dlfiz** [comment] 2023-05-27 23:14
Yes IPs are OK. The test commands also work fine for all states, just not powering off like it used to on shutdown. 
**Log** https://pastebin.com/dN4DHiyZ
**Config** https://pastebin.com/sPuyimNV

**Comment by JPersson77** [comment] 2023-05-28 08:18
Hi @dlfiz the issue is reported already and additional validation is patched and will be in the  next release. To sort it please go to the global options and review the "restart words", specifically ensure only "restart" is checked

**Comment by dlfiz** [comment] 2023-05-28 08:48
Great thank you and thank you for the application 👍

**Closed** 2023-06-09 20:03 UTC
